INSERT INTO `personnel_awards` (`id`, `tabel_no`, `award_id`, `reason`, `given_date`) VALUES
                                                                                          (12, 'IT0002', 2002, 'yeni il', '2023-12-10'),
                                                                                          (14, 'PQ0010', 2002, 'yeni il', '2023-12-10'),
                                                                                          (15, 'PQ0010', 2004, 'test', '2023-03-20'),
                                                                                          (18, 'IT0002', 2003, 'sdasd', '2023-10-19'),
                                                                                          (20, 'PQ0010', 2003, 'sdsd', '2023-10-19'),
                                                                                          (21, 'IT0002', 2004, 'test', '2023-03-20'),
                                                                                          (29, 'PQ0010', 2001, '3qewr23', '2023-12-12');

INSERT INTO `personnel_education` (`id`, `tabel_no`, `educational_institution_id`, `education_form_id`, `education_language`, `specialty`, `admission_year`, `graduated_year`, `profession_by_document`, `diplom_serie`, `diplom_no`, `diplom_given_date`, `coefficient`, `calculate_as_seniority`) VALUES
                                                                                                                                                                                                                                                                                                        (6, 'PQ0010', 10, 10, 'Azerbaycan', 'Komputer elmleri', '2019-09-10', '2023-07-10', 'BIM', 'D', 2342343, '2015-10-02', 0.50, 1),
                                                                                                                                                                                                                                                                                                        (7, 'IT0002', 10, 10, 'Azerbaycan', 'Iqtisadiyyat', '2015-08-02', '2019-08-06', 'BIM', 'D', 344233, '2023-10-01', NULL, 0);

INSERT INTO `personnel_extra_education` (`id`, `tabel_no`, `education_type_id`, `educational_institution_id`, `education_form_id`, `name`, `shortname`, `education_language`, `education_program_name`, `admission_year`, `graduated_year`, `education_document_type_id`, `diplom_serie`, `diplom_no`, `diplom_given_date`, `coefficient`, `calculate_as_seniority`) VALUES
                                                                                                                                                                                                                                                                                                                                                                         (2, 'PQ0010', 10, 10, 20, 'Bakı Dövlət Universiteti', 'BDU', 'Azerbaycan', 'Magistr', '2019-08-22', '2023-07-25', 10, 'D', 3242423, '2023-10-02', NULL, 0),
                                                                                                                                                                                                                                                                                                                                                                         (3, 'IT0002', 10, 10, 20, 'Bakı Dövlət Universiteti', 'BDU', 'Ingilis', 'MBA', '2021-11-03', '2023-12-14', 10, 'M', 24234234, '2023-12-16', 0.50, 1),
                                                                                                                                                                                                                                                                                                                                                                         (4, 'PQ0010', 20, 10, 20, 'Bakı Dövlət Universiteti', 'BDU', 'Ingilis', 'Elave', '2015-10-07', '2018-10-09', 10, 'E', 2342342, '2018-12-05', 0.50, 1);

INSERT INTO `personnel_foreign_languages` (`id`, `tabel_no`, `language_id`, `knowledge_status`) VALUES
                                                                                                    (1, 'PQ0010', 10, 'sərbəst'),
                                                                                                    (2, 'PQ0010', 30, 'yaxşı'),
                                                                                                    (3, 'PQ0010', 20, 'zəif');

INSERT INTO `personnel_identity_documents` (`id`, `tabel_no`, `nationality_id`, `series`, `number`, `pin`, `born_country_id`, `born_city_id`, `registered_address`, `is_married`, `military_duty`, `blood_group`, `eye_color`, `height`, `document_issued_authority`, `document_issued_date`) VALUES
    (9, 'PQ0010', 11, 'AA', '546456', '1071F12', 11, 1101, 'Bakixanov Sakit Qocayev Teras park', 1, 'h/m', '2+', 'qara', 173, 'ASAN 2', '2014-05-18');

INSERT INTO `personnel_kinships` (`id`, `tabel_no`, `kinship_id`, `fullname`, `birthdate`, `birth_place`, `company_name`, `position`, `registered_address`, `residental_address`) VALUES
                                                                                                                                                                                      (7, 'PQ0010', 11, 'Sadiqov Ismayil Calal oglu', '1962-10-01', 'Vedi', 'Tehsil institutu', 'Sobe mudiri', 'Bayil', 'Bayil'),
                                                                                                                                                                                      (8, 'PQ0010', 12, 'Sadiqova Xatire Abbas qizi', '1968-05-22', 'Naxcivan Serur', '49 nomreli mekteb', 'Muellime', 'Bayil', 'Bayil'),
                                                                                                                                                                                      (9, 'PQ0010', 13, 'Calalli Alpay Ismayil oglu', '2005-10-02', 'Baki', 'Texniki Universitet', 'telebe', 'Bayil', 'Bayil');

INSERT INTO `personnel_labor_activities` (`id`, `tabel_no`, `company_name`, `position`, `coefficient`, `join_date`, `leave_date`) VALUES
                                                                                                                                      (34, 'PQ0010', 'MHM', 'proqramci', NULL, '2012-07-01', '2019-08-01'),
                                                                                                                                      (35, 'PQ0010', 'A2Z', 'proqramci', 2.00, '2019-10-01', '2022-07-01'),
                                                                                                                                      (36, 'PQ0010', 'IBP', 'proqramci', NULL, '2022-08-25', '2023-10-10'),
                                                                                                                                      (38, 'IT0002', 'Demiryolu', 'IT', NULL, '2022-10-02', '2023-10-02'),
                                                                                                                                      (39, 'IT0002', 'Azersu', 'IT', NULL, '2023-12-03', '2021-12-06'),
                                                                                                                                      (40, 'PQ0010', 'Mudafie Nazirliyi', 'Bas zabit', 2.00, '2013-06-02', '2018-12-27');

INSERT INTO `personnel_military_services` (`id`, `tabel_no`, `attitude_to_military_service`, `rank_id`, `given_date`, `start_date`, `end_date`) VALUES
                                                                                                                                                    (4, 'PQ0010', 'musbet', 10, '2023-10-09', '2014-08-23', '2015-07-01'),
                                                                                                                                                    (6, 'IT0002', 'musbet', 10, '2023-08-06', '2022-10-11', '2023-11-06'),
                                                                                                                                                    (7, 'PQ0010', 'musbet', 20, '2021-12-01', '2014-08-06', '2015-08-03');

INSERT INTO `personnel_participation_events` (`id`, `tabel_no`, `event_type`, `event_name`, `event_date`) VALUES
                                                                                                              (2, 'PQ0010', 'Ingilis kursu', 'English level', '2023-10-01 00:00:00'),
                                                                                                              (3, 'PQ0010', 'Proqramlasdirma', 'PHP Laravel', '2023-10-30 00:00:00');

INSERT INTO `personnel_punishments` (`id`, `tabel_no`, `punishment_id`, `reason`, `given_date`, `expired_date`) VALUES
                                                                                                                    (7, 'PQ0010', 9006, 'Geyim formasi duzgun deyildi', '2023-09-03', '2023-12-03'),
                                                                                                                    (9, 'IT0002', 9029, '323', '2023-12-11', '2023-12-13');

INSERT INTO `personnel_ranks` (`id`, `tabel_no`, `rank_id`, `name`, `given_date`) VALUES
                                                                                      (20, 'IT0002', 10, 'rutbe2', '2023-12-04'),
                                                                                      (21, 'PQ0010', 10, 'rutbe', '2023-12-04');

INSERT INTO `personnels` (`id`, `tabel_no`, `surname`, `name`, `patronymic`, `photo`, `has_changed_initials`, `previous_surname`, `previous_name`, `previous_patronymic`, `initials_changed_date`, `initials_change_reason`, `birthdate`, `gender`, `phone`, `mobile`, `email`, `nationality_id`, `has_changed_nationality`, `previous_nationality_id`, `nationality_changed_date`, `nationality_change_reason`, `pin`, `residental_address`, `registered_address`, `education_degree_id`, `structure_id`, `position_id`, `work_norm_id`, `join_work_date`, `leave_work_date`, `disability_id`, `disability_given_date`, `extra_important_information`, `computer_knowledge`, `added_by`, `deleted_by`, `deleted_at`, `created_at`, `updated_at`) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (15, 'PQ0010', 'Calalli', 'Togrul', 'Ismayil', 'personnel/Q0T8mtNGM1dbd8kRy9jQohjUGQt9P3NmiIhNduqf.jpg', 0, NULL, NULL, NULL, NULL, NULL, '1993-10-08', 1, '0502115884', '0502115884', 'toghrul.calalli@gmail.com', 11, 0, NULL, NULL, NULL, '1071F12', 'Teras park Bakixanov', 'Bayil Mikayil Huseynov', 100, 3, 21, 10, '2023-09-20', NULL, NULL, NULL, NULL, 'Ela', 1, NULL, NULL, '2023-10-16 02:25:34', '2023-12-01 12:05:15'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (16, 'IT0002', 'Mammadli', 'Bahruz', 'Arif', 'personnel/sjVbR6cfddkH9Hecl0wwc3xeHXjAmejRWhDwJz5P.jpg', 0, NULL, NULL, NULL, NULL, NULL, '1983-10-01', 1, '0502403040', '0502403040', 'bahruz@gmail.com', 11, 0, NULL, NULL, NULL, '654DS78', 'Bayil', 'Bayil', 100, 3, 10, 10, '2021-10-06', NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, '2023-10-21 15:56:43', '2023-12-13 18:05:17'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (17, 'CX0001', 'Zeynalov', 'Orxan', 'Akif', NULL, 0, NULL, NULL, NULL, NULL, NULL, '1993-10-04', 1, '012-xxx-xx-xx', '050-xxx-xx-xx', 'orxan@gmail.com', 11, 0, NULL, NULL, NULL, '545sd34', '28 may', '28 may', 10, 2, 31, 10, '2021-10-01', '2023-10-15', NULL, NULL, 'Xestelik', NULL, 1, NULL, NULL, '2023-10-22 19:44:58', '2023-10-22 19:44:58'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (19, 'T2323', 'test', 'Test', 'test', NULL, 0, NULL, NULL, NULL, NULL, NULL, '2023-10-01', 2, '3432432', '3423423', 'test@test.com', 63, 0, NULL, NULL, NULL, '654DS78', 'sadasd', 'asdasda', 10, 6, 21, 10, '2023-10-16', NULL, NULL, NULL, NULL, NULL, 1, 1, '2023-10-28 14:26:09', '2023-10-28 02:43:58', '2023-10-28 14:26:09'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (20, 'PQ0002', 'Zamanli', 'Turan', 'Islam', NULL, 0, NULL, NULL, NULL, NULL, NULL, '1993-10-08', 1, '012-xxx-xx-xx', '050-xxx-xx-xx', 'turanzamanli@gmail.com', 11, 0, NULL, NULL, NULL, '545sd32', 'Suraxani', 'Suraxani', 100, 5, 21, 10, '2023-11-12', NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, '2023-12-16 22:51:45', '2023-12-16 23:28:21');
