<div>
    <x-modal-delete
        livewire-event-to-open-modal="deletePersonnelWasSet"
        event-to-close-modal="personnelWasDeleted"
        :modal-title="__('personnel::common.titles.delete_personnel')"
        :modal-description="__('personnel::common.messages.delete_data_confirm')"
        :modal-confirm-button-text="__('personnel::common.actions.delete')"
        wire-click="deletePersonnel"
    />
</div>
