<?php

return [
    'menu_items' => [
        ['label' => 'admin::references.menu.appeal_statuses', 'icon' => 'info-circle-icon', 'route' => 'admin.appeal-status'],
        ['label' => 'admin::references.menu.awards', 'icon' => 'gift-icon', 'route' => 'admin.awards'],
        ['label' => 'admin::references.menu.cities', 'icon' => 'road-icon', 'route' => 'admin.cities'],
        ['label' => 'admin::references.menu.countries', 'icon' => 'world-icon', 'route' => 'admin.countries'],
        ['label' => 'admin::references.menu.education_degree', 'icon' => 'stairs-icon', 'route' => 'admin.education-degrees'],
        ['label' => 'admin::references.menu.document_type', 'icon' => 'book-icon', 'route' => 'admin.document-types'],
        ['label' => 'admin::references.menu.education_form', 'icon' => 'library-icon', 'route' => 'admin.education-forms'],
        ['label' => 'admin::references.menu.education_type', 'icon' => 'briefcase-icon', 'route' => 'admin.education-types'],
        ['label' => 'admin::references.menu.universities', 'icon' => 'home-icon', 'route' => 'admin.educational-institutions'],
        ['label' => 'admin::references.menu.leave_types', 'icon' => 'folder-plus-icon', 'route' => 'admin.leave-types'],
        ['label' => 'admin::references.menu.kinships', 'icon' => 'users-icon', 'route' => 'admin.kinship'],
        ['label' => 'admin::references.menu.order_categories', 'icon' => 'category-icon', 'route' => 'admin.order-categories'],
        ['label' => 'admin::references.menu.order_statuses', 'icon' => 'recover', 'route' => 'admin.order-statuses'],
        ['label' => 'admin::references.menu.position', 'icon' => 'chair-icon', 'route' => 'admin.positions'],
        ['label' => 'admin::references.menu.structure', 'icon' => 'structure-icon', 'route' => 'admin.structures'],
        ['label' => 'admin::references.menu.punishments', 'icon' => 'voltage-icon', 'route' => 'admin.punishments'],
        ['label' => 'admin::references.menu.weapons', 'icon' => 'fire-icon', 'route' => 'admin.weapons'],
        ['label' => 'admin::references.menu.work_norms', 'icon' => 'timer-icon', 'route' => 'admin.work-norms'],
        ['label' => 'admin::references.menu.languages', 'icon' => 'globe-icon', 'route' => 'admin.languages'],
        ['label' => 'admin::references.menu.scientific_degree_and_names', 'icon' => 'pen-ruler-icon', 'route' => 'admin.scientific-degrees'],
        ['label' => 'admin::references.menu.social_origin', 'icon' => 'shield-user-icon', 'route' => 'admin.social-origins'],
        ['label' => 'admin::references.menu.rank_reasons', 'icon' => 'double-arrow-icon', 'route' => 'admin.rank-reasons'],
        ['label' => 'admin::references.menu.rank_category', 'icon' => 'arrow-icon', 'route' => 'admin.rank-categories'],
        ['label' => 'admin::references.menu.approval_routes', 'icon' => 'network-icon', 'route' => 'admin.self-service-approval-routes'],
        ['label' => 'admin::references.menu.hr_policy_diagnostics', 'icon' => 'settings-icon', 'route' => 'admin.hr-policy-diagnostics'],
    ],
];
