<?php

return [
    'global' => [
        [
            'id' => 1,
            'name' => 'Staff table',
            'icon' => 'network-icon',
            'color' => 'zinc',
            'order' => 1,
            'is_active' => 1,
            'url' => 'staffs',
            'permission_id' => 1,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 2,
            'name' => 'Orders',
            'icon' => 'line-order-icon',
            'color' => 'zinc',
            'order' => 2,
            'is_active' => 1,
            'url' => 'orders',
            'permission_id' => 8,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 3,
            'name' => 'Personal affairs',
            'icon' => 'personal-affair-icon',
            'color' => 'zinc',
            'order' => 3,
            'is_active' => 1,
            'url' => 'home',
            'permission_id' => 12,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 4,
            'name' => 'Reports',
            'icon' => 'report-chart-icon',
            'color' => 'zinc',
            'order' => 9,
            'is_active' => 1,
            'url' => 'home',
            'permission_id' => 3,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 5,
            'name' => 'Queries',
            'icon' => 'admin-icon',
            'color' => 'zinc',
            'order' => 21,
            'is_active' => 0,
            'url' => 'home',
            'permission_id' => 3,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 7,
            'name' => 'Candidates',
            'icon' => 'candidate-icon',
            'color' => 'zinc',
            'order' => 4,
            'is_active' => 1,
            'url' => 'candidates',
            'permission_id' => 17,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 8,
            'name' => 'Vacations',
            'icon' => 'vacation-icon',
            'color' => 'zinc',
            'order' => 5,
            'is_active' => 1,
            'url' => 'vacations.list',
            'permission_id' => 25,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 9,
            'name' => 'Business trips',
            'icon' => 'holiday-icon',
            'color' => 'zinc',
            'order' => 6,
            'is_active' => 1,
            'url' => 'business-trips.list',
            'permission_id' => 21,
            'types' => ['military', 'public', 'private'],
        ],
        [
            'id' => 10,
            'name' => 'Time off',
            'icon' => 'calendar-icon',
            'color' => 'zinc',
            'order' => 8,
            'is_active' => 1,
            'url' => 'leaves',
            'permission_id' => 41,
            'types' => ['military', 'public', 'private'],
        ],
    ],
];
